services:
  rails:
    image: ruby
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/rails s"
    environment:
      BINDING: 0.0.0.0
      LANG: C.UTF-8
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/workspace
      - gem-data:/usr/local/bundle
    working_dir: /workspace

volumes:
  gem-data:
