version: "3.9"

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"

volumes:
  mongo-data:
