version: "3.9"

services:
  python:
    image: python
    volumes:
      - .:/workspace
      - bin-data:/usr/local/bin
      - pip-data:/usr/local/lib
    working_dir: /workspace

volumes:
  bin-data:
  pip-data:
