#!/bin/sh

dump() {
  cat /dcy-cli/dump/$1.yml
}

help() {
  cat /dcy-cli/help.txt
}

list() {
  echo dump
  ls /dcy-cli/dump/ | xargs -I{} sh -c 'echo - ${0%.*}' {}
  echo setup
  ls /dcy-cli/setup/ | xargs -I{} sh -c 'echo - ${0%.*}' {}
}

setup() {
  cat /dcy-cli/setup/$1.sh
}

$@
